Taetse/fast compression
moya-app/traefik-custom-patches pull request #5
Opened 2024-08-15 19:13 UTC by Taetse

### What does this PR do?

### Motivation

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

2024-08-26 20:09 UTC, mzealey reviewed
good job, few todos below. Also please bump to latest (1.17.9) of the zstd lib, and do a proper rebase of this onto the v3.1 branch rather than merge-commit.

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/zstd.go
> +	z.writer.Close()
do we need to check for err here?

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/zstd.go
> +		decoderOptions = append(decoderOptions, zstd.WithDecoderDicts(dict))
standardize this code with the other constructor (I don't mind which approach you follow but just try to make the code mirror each other in both?)

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/zstd.go
> +		uncompressedData := make([]byte, z.chunkSize)
Better for performance if this can be stack allocated rather than via `make()`? so just something like:

```
const CHUCK_SIZE = 4 * 1024
var uncompressedData [CHUNK_SIZE]byte
```

sort of thing? Any reason `CHUNK_SIZE` shouldn't just be compiled in?

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/zstd.go
> +			connEr = z.writer.Flush()
```suggestion
			// Force a flush to trigger a send of the compressed stanza/data downstream, otherwise it could hang
			connEr = z.writer.Flush()
```

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/stream_compress_test.go
> +	compressor, err := New(context.Background(), decompressor, compressorConfig, "traefikTest")
```suggestion
        // Pipeline is now compressor -> decompressor -> echo function
	compressor, err := New(context.Background(), decompressor, compressorConfig, "traefikTest")
```

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/stream_compress_test.go
> +	compressor, err := New(context.Background(), decompressor, compressorConfig, "traefikTest")
Pop something in between to ensure that the traffic is actually compressed? Otherwise compression may be a noop?

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/stream_compress_test.go
> +func TestStreamCompress_ServeTCPCompression(t *testing.T) {
add some comments on these fns to say what they are testing please - code is a bit tricky for me to read

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/stream_compress_test.go
> +	serverDecompressor, err := zstd.NewReader(server)
perhaps do this & the below without using the reader/pipe funs but rather generate bytestream with `EncodeAll()` zstd lib fn and then pass it as a byte string to the server and back again to ensure it is working correctly?

2024-08-26 20:09 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/stream_compress_test.go
> +}
Could you please add some automated benchmarking functions here also? 2 examples come to mind:

1. spin up configurable number (eg default of 10000) independent connections to a server, send and receive 50kb of data, measure overall golang memory usage and time
2. wrap-nest configurable (eg 100) decoder/encoders in a pipeline on single connection, send data through and measure mem usage and time. I believe this is the test you've been doing and automating locally anyway?

2024-08-28 01:02 UTC, Taetse commented
> good job, few todos below. Also please bump to latest (1.17.9) of the zstd lib, and do a proper rebase of this onto the v3.1 branch rather than merge-commit.

The zstd lib is already on latest version due to traefik using it as well

2024-09-03 19:05 UTC, mzealey commented on pkg/middlewares/tcp/streamcompress/stream_compress_test.go
> +}
ok thanks can you put results of this in the ticket? perhaps a few to see how (1) scales with number of clients? (& mem usage..)

2024-09-09 08:18 UTC, mzealey requested changes
waiting on final comment

2024-09-13 08:02 UTC, merged